root: true

parser: '@typescript-eslint/parser'

settings:
  react:
    version: 'detect'
  import/resolver:
    node:
      moduleDirectory:
        - 'node_modules'
        - 'src'
      extensions:
        - '.js'
        - '.jsx'
        - '.ts'
        - '.tsx'

plugins:
  - '@typescript-eslint'
  - 'prettier'

extends:
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:prettier/recommended'
  # - 'prettier/@typescript-eslint'
  # - 'prettier/react'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'

env:
  browser: true
  commonjs: true
  es6: true
  node: true

globals:
  strapi: true

rules:
  react/no-unescaped-entities: 'off'
  # allow 'default' exports
  react/display-name: 'off'
  react/prop-types: 'off'
  # turn off base rule to avoid conflicts
  no-use-before-define: 'off'
  '@typescript-eslint/no-use-before-define': 'error'
  '@typescript-eslint/explicit-function-return-type':
    - 'error'
    - allowExpressions: true
      allowTypedFunctionExpressions: true
  no-undef: 0
  prettier/prettier: # 2
    - 'error'
    - endOfLine: 'auto'
  no-console: 'warn'
  '@typescript-eslint/no-unused-vars':
    - 'warn'
    - argsIgnorePattern: '^_'
  linebreak-style:
    - 'error'
    - 'unix'
  quotes:
    - 'error'
    - 'single'
  semi:
    - 'error'
    - 'always'
